# Generated by Django 4.2.19 on 2025-03-02 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to=settings.AUTH_USER_MODEL)),
                ('offered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_trades', to='products.product')),
                ('requested_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_trades', to='products.product')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
