# Generated by Django 4.2.19 on 2025-02-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='representative',
        ),
    ]
