# Generated by Django 4.2.19 on 2025-03-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_customer_product_representative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
